# kaspa-channel voucher crypto + wire format. The rust vector below was generated by the
# reference covenant tooling (channel_cycle.rs, rust-secp256k1) — it pins cross-implementation
# compatibility: a voucher signed by any BIP340 stack must verify here, and vice versa.
import pytest

from k402.channel import (format_channel_header, parse_channel_header, payer_pubkey_from_privkey,
                          sign_voucher, verify_voucher, voucher_message)
from k402.schemes import ChannelOffer, parse_offers, payment_required_body

# rust-secp256k1 vector: privkey e1*32, covid ab*32, total 123456789
RUST_PRIV = "e1" * 32
RUST_PUB = "07031187fb14f770d521389c502321abb0e41e5ab87181d24e8faa0aeed83798"
CID = "ab" * 32
TOTAL = 123456789
RUST_SIG = ("05edd3819b0cef5cf91c76a29b9408388e7cf46782116c5967ce917d955c1bfb"
            "49ef37d3f7f13ac7156dffcdbaf85a4b7836a33a2c36d8255997c9b5da126789")


def test_message_layout_matches_covenant():
    # covenant parses: (byte[32] cid, byte[8] total_le) = msg.split(32)
    assert voucher_message(CID, TOTAL).hex() == "ab" * 32 + "15cd5b0700000000"


def test_rust_signed_voucher_verifies():
    assert verify_voucher(RUST_PUB, CID, TOTAL, RUST_SIG)


def test_pubkey_derivation_matches_rust():
    assert payer_pubkey_from_privkey(RUST_PRIV) == RUST_PUB


def test_python_sign_roundtrip():
    sig = sign_voucher(RUST_PRIV, CID, TOTAL)
    assert verify_voucher(RUST_PUB, CID, TOTAL, sig)


def test_wrong_total_rejected():
    assert not verify_voucher(RUST_PUB, CID, TOTAL + 1, RUST_SIG)


def test_wrong_channel_rejected():
    assert not verify_voucher(RUST_PUB, "cd" * 32, TOTAL, RUST_SIG)


def test_tampered_sig_rejected():
    bad = RUST_SIG[:-2] + ("00" if RUST_SIG[-2:] != "00" else "01")
    assert not verify_voucher(RUST_PUB, CID, TOTAL, bad)


def test_garbage_inputs_do_not_raise():
    assert not verify_voucher("zz", CID, TOTAL, RUST_SIG)
    assert not verify_voucher(RUST_PUB, CID, TOTAL, "00" * 64)


def test_header_roundtrip():
    h = format_channel_header(CID, TOTAL, RUST_SIG)
    assert parse_channel_header(h) == (CID, TOTAL, RUST_SIG)
    with pytest.raises(ValueError):
        parse_channel_header("kaspa-channel too few")


def test_channel_offer_roundtrip_and_parse():
    offer = ChannelOffer(network="mainnet", payee_pubkey="14" * 32, price_sompi="3000000",
                         min_channel_sompi="100000000", max_channel_sompi="500000000",
                         min_expiry_daa_delta=86400, maxfee_sompi="5000000", open="/channel/open")
    body = payment_required_body([offer])
    parsed = parse_offers(body)
    assert len(parsed) == 1 and isinstance(parsed[0], ChannelOffer)
    assert parsed[0].to_dict() == offer.to_dict()
